// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200413061409_EndMarksTablosuEklendi")]
    partial class EndMarksTablosuEklendi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.CellRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ColumnIndex");

                    b.Property<string>("Data");

                    b.Property<DateTime>("Date");

                    b.Property<string>("FileName");

                    b.Property<int>("RowIndex");

                    b.Property<int>("TableIndex");

                    b.Property<string>("TemplateName");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("RowIndex", "ColumnIndex", "FileName", "TableIndex")
                        .IsUnique()
                        .HasFilter("[FileName] IS NOT NULL");

                    b.ToTable("CellRecords");
                });

            modelBuilder.Entity("WebApplication1.Models.DbModels.Default", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Defaults");
                });

            modelBuilder.Entity("WebApplication1.Models.DbModels.EndMark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ColumnIndex");

                    b.Property<int>("RowIndex");

                    b.Property<int>("SheetIndex");

                    b.Property<string>("TemplateName");

                    b.HasKey("Id");

                    b.ToTable("EndMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
